# Generated by Django 5.2.1 on 2025-05-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('orders', '0002_remove_commande_id_commande_commande_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddoc',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.commande'),
        ),
    ]
