# Generated by Django 5.2.1 on 2025-05-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordonneeBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(max_length=50)),
                ('code_banque', models.CharField(max_length=6)),
                ('code_guichet', models.CharField(max_length=6)),
                ('num_compte', models.CharField(max_length=20)),
                ('cle', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('unite', models.CharField(choices=[('kg', 'Kg'), ('pièce', 'Pièce')], max_length=20, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis.categorie')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('unite', models.CharField(choices=[('kg', 'Kg'), ('pièce', 'Pièce')], max_length=20, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proforma.produit')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proforma.produitquote')),
            ],
        ),
        migrations.AddField(
            model_name='produitquote',
            name='produits',
            field=models.ManyToManyField(through='proforma.ProduitQuoteItem', to='proforma.produit'),
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalites_reglement', models.TextField()),
                ('condition_ht', models.TextField(blank=True, null=True)),
                ('montant_total_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_a_payer_lettres', models.CharField(blank=True, max_length=255)),
                ('commentaire_refus', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('valide', 'Validée'), ('non_valide', 'Non Validée')], default='en_attente', max_length=20)),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devis.devisnouveauproduit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='proforma_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proforma.proforma'),
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('unite', models.CharField(choices=[('kg', 'Kg'), ('pièce', 'Pièce')], max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proforma.produit')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma.proforma')),
            ],
        ),
    ]
