# Generated by Django 5.2.1 on 2025-05-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitquote',
            name='produits',
        ),
        migrations.AddField(
            model_name='produitquote',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('envoye_be', 'Envoyé au BE'), ('en_traitement', 'En traitement'), ('proforma_envoyee', 'Proforma envoyée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='proforma',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proforma.produitquote'),
        ),
        migrations.AlterField(
            model_name='produitquoteitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma.produitquote'),
        ),
    ]
