# Generated by Django 5.2.1 on 2025-05-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0002_remove_produitquote_produits_produitquote_statut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proforma',
            old_name='commentaire_refus',
            new_name='commentaire_refus_client',
        ),
        migrations.AddField(
            model_name='proforma',
            name='commentaire_refus_cmc',
            field=models.TextField(blank=True),
        ),
    ]
