# Generated by Django 5.2.1 on 2025-05-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0003_rename_commentaire_refus_proforma_commentaire_refus_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('valide', 'Validée par le CMC'), ('non_valide', 'Non Validée par le CMC')], default='en_attente', max_length=20),
        ),
    ]
