# Generated by Django 5.2.1 on 2025-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0006_alter_proforma_devis_alter_proforma_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitquote',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_traitement', 'En traitement'), ('proforma_envoyee', 'Proforma envoyée')], default='en_attente', max_length=20),
        ),
    ]
