# Generated by Django 5.2.1 on 2025-05-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseTechniqueBE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_support_longueur', models.FloatField(blank=True, null=True)),
                ('format_support_largeur', models.FloatField(blank=True, null=True)),
                ('type_impression', models.CharField(blank=True, max_length=100, null=True)),
                ('sens_impression', models.CharField(blank=True, max_length=100, null=True)),
                ('type_encre', models.CharField(blank=True, max_length=100, null=True)),
                ('dorure', models.CharField(blank=True, max_length=100, null=True)),
                ('colle_complexage', models.CharField(blank=True, max_length=100, null=True)),
                ('plastification', models.CharField(blank=True, max_length=100, null=True)),
                ('decoupe', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FinitionConditionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_utilisation', models.TextField(choices=[('utilisation automatique', 'Utilisation Automatique'), ('utilisation manuelle', 'Utilisation Manuelle')])),
                ('mode_livraison', models.TextField(choices=[('bobine', 'Bobine'), ('sachet', 'Sachet'), ('piece_format', 'Piece au format'), ('planche', 'Planche'), ('au_choix', 'Au choix')])),
                ('sens_deroulement', models.CharField(blank=True, choices=[('A1', 'A/1'), ('B1', 'B/1'), ('C1', 'C/1'), ('D1', 'D/1'), ('A2', 'A/2'), ('B2', 'B/2'), ('C2', 'C/2'), ('D2', 'D/2')], max_length=100, null=True)),
                ('nature_mandrin', models.CharField(blank=True, choices=[('carton', 'Carton'), ('pvc', 'PVC')], max_length=100, null=True)),
                ('diametre_mandrin', models.CharField(blank=True, choices=[('40mm', '40 mm'), ('76mm', '76 mm'), ('152mm', '152 mm'), ('autres', 'Autres')], null=True)),
                ('epaisseur_mandrin', models.FloatField(blank=True, null=True)),
                ('poids_max_bobine', models.FloatField(blank=True, null=True)),
                ('diametre_bobine', models.FloatField(blank=True, null=True)),
                ('nb_bobines_par_palette', models.PositiveIntegerField(blank=True, null=True)),
                ('autocolant_utilise', models.BooleanField(default=False)),
                ('espace_pose_min', models.FloatField(blank=True, null=True)),
                ('espace_pose_max', models.FloatField(blank=True, null=True)),
                ('contenant', models.CharField(blank=True, choices=[('carton', 'Carton'), ('pile', 'Pile'), ('paquet', 'Paquet')], help_text="Vous n'aurez pas forcement besoin de choisir un contenant si vous avez choisir la bobine comme mode de livraison", null=True)),
                ('conditionnement', models.CharField(choices=[('film_etirable', 'Film Etirable'), ('film_pe', 'Film PE'), ('carton', 'Carton'), ('film_pe_carton', 'Film PE et Carton'), ('film_etirable_carton', 'Film Etirable et Carton'), ('autres', 'Autres')], max_length=100)),
                ('nb_pieces', models.PositiveIntegerField(blank=True, help_text='Donner le nombre de pièces par bobine,par carton, par parquet ou par pile dependant de ce que vous avez choisi', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coloration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(blank=True, max_length=20, null=True)),
                ('analyseTech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devis.analysetechniquebe')),
            ],
        ),
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotation_unitaire', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantite', models.PositiveIntegerField(null=True)),
                ('taux_mat', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('analyseBe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devis.analysetechniquebe')),
            ],
        ),
        migrations.CreateModel(
            name='DevisNouveauProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_produit', models.CharField(max_length=255)),
                ('quantite_previsionnelle', models.IntegerField()),
                ('unite', models.CharField(choices=[('kg', 'Kg'), ('pièce', 'Pièce')], max_length=20)),
                ('periode', models.CharField(choices=[('mois', 'Mois'), ('semaine', 'Semaine'), ('trimestre', 'Trimestre'), ('semestre', 'Semestre'), ('année', 'Année')], max_length=20)),
                ('fiche_technique', models.BooleanField(default=False)),
                ('echantillon_disponible', models.BooleanField(default=False)),
                ('visuel_disponible', models.BooleanField(default=False)),
                ('devis_identique', models.BooleanField(default=False)),
                ('accessoires_payants', models.BooleanField(default=False)),
                ('longueur_produit', models.FloatField(help_text='en mm')),
                ('largeur_produit', models.FloatField(help_text='en mm')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_traitement', 'En traitement'), ('envoye_be', 'Nouveau Devis'), ('en_traitement_be', 'En cour de traitement'), ('complet', 'Devis Complet')], default='nouveau', max_length=30)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('traitement_date', models.DateTimeField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('analyseBE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devis.analysetechniquebe')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='accounts.client')),
                ('famille_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devis.categorie')),
                ('generated_doc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.generateddoc')),
                ('finition_conditionnement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devis.finitionconditionnement')),
            ],
        ),
        migrations.CreateModel(
            name='Outillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_outillage', models.CharField(choices=[('cylindre', "Cylindre d'impression"), ('cliche', "Cliché d'impression"), ('plaque_decoupe', 'Plaque de découpe'), ('plaque_dorure', 'Plaque de dorure'), ('emporte_piece', 'Emporte pièce')], max_length=50, null=True)),
                ('quantite', models.PositiveIntegerField(null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('analyse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devis.analysetechniquebe')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_support', models.CharField(blank=True, max_length=100, null=True)),
                ('couleur', models.CharField(blank=True, max_length=50, null=True)),
                ('epaisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grammage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='devis.devisnouveauproduit')),
            ],
        ),
    ]
