# Generated by Django 5.2.1 on 2025-05-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_alter_devisnouveauproduit_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finitionconditionnement',
            name='contenant',
            field=models.CharField(blank=True, choices=[('carton', 'Carton'), ('pile', 'Pile'), ('paquet', 'Paquet')], help_text="Vous n'aurez pas forcement besoin de choisir un contenant si vous avez choisir la bobine comme mode de livraison", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finitionconditionnement',
            name='diametre_mandrin',
            field=models.CharField(blank=True, choices=[('40mm', '40 mm'), ('76mm', '76 mm'), ('152mm', '152 mm'), ('autres', 'Autres')], max_length=100, null=True),
        ),
    ]
