# Generated by Django 5.2.1 on 2025-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_alter_finitionconditionnement_contenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='taux_mat',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
