# Generated by Django 5.2.1 on 2025-05-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('prix_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_livraison', models.DateField()),
                ('requiert_certificat_analyse', models.BooleanField(default=False)),
                ('requiert_attestation', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('received', 'Reçu'), ('delivered', 'Livré'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='accounts.client')),
            ],
        ),
    ]
