# Generated by Django 5.2.1 on 2025-05-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('proforma', '0004_alter_proforma_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='commande',
            name='proforma',
            field=models.ForeignKey(limit_choices_to={'statut': 'acceptee'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='proforma.proforma'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepted', 'Acceptée'), ('delivered', 'Livrée'), ('rejected', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
